name: tests

on:
  push:
    branches:
      - master      
    tags:
      - "*"
    paths-ignore:
      - "docs/**"
  pull_request:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: ["ubuntu-latest"]
        include:
          - python-version: "3.9"
            os: "macos-latest"
          - python-version: "3.9"
            os: "windows-latest"	    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -r requirements.txt
  upload_pypi:
    needs: [build]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: ${{ secrets.token_pypi }}
          password: ${{ secrets.password_pypi }}